<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AllInterface">
      <HintPath>..\..\..\AllInterface\AllInterface\bin\Debug\net6.0\AllInterface.dll</HintPath>
    </Reference>
    <Reference Include="Task-16">
      <HintPath>..\..\task-16 int\task-16\bin\Debug\net6.0\Task-16.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
